-- MySQL Script generated by MySQL Workbench
-- So 01 Feb 2015 20:41:05 CET
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema curcal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `curcal` ;
CREATE SCHEMA IF NOT EXISTS `curcal` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `curcal` ;

-- -----------------------------------------------------
-- Table `curcal`.`currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curcal`.`currency` ;

CREATE TABLE IF NOT EXISTS `curcal`.`currency` (
  `currency_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(3) NULL,
  `sign` VARCHAR(10) NULL,
  PRIMARY KEY (`currency_id`),
  UNIQUE INDEX `currency_id_UNIQUE` (`currency_id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `curcal`.`exchange_rate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curcal`.`exchange_rate` ;

CREATE TABLE IF NOT EXISTS `curcal`.`exchange_rate` (
  `exchange_rate_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_currency_from` INT UNSIGNED NOT NULL,
  `id_currency_to` INT UNSIGNED NOT NULL,
  `rate` DOUBLE NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`exchange_rate_id`),
  UNIQUE INDEX `id_UNIQUE` (`exchange_rate_id` ASC),
  INDEX `fk_exchange_rate_currency_idx` (`id_currency_from` ASC),
  INDEX `fk_exchange_rate_currency1_idx` (`id_currency_to` ASC),
  CONSTRAINT `fk_exchange_rate_currency`
    FOREIGN KEY (`id_currency_from`)
    REFERENCES `curcal`.`currency` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exchange_rate_currency1`
    FOREIGN KEY (`id_currency_to`)
    REFERENCES `curcal`.`currency` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `curcal` ;

-- -----------------------------------------------------
-- Placeholder table for view `curcal`.`ex_rates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curcal`.`ex_rates` (`id` INT, `rate` INT, `from_id` INT, `from_code` INT, `from_sign` INT, `to_id` INT, `to_code` INT, `to_sign` INT, `created_at` INT);

-- -----------------------------------------------------
-- View `curcal`.`ex_rates`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `curcal`.`ex_rates` ;
DROP TABLE IF EXISTS `curcal`.`ex_rates`;
USE `curcal`;
CREATE  OR REPLACE VIEW `ex_rates` AS
select 
	ex.exchange_rate_id AS id,
	ex.rate,

	cf.currency_id AS from_id,
	cf.code AS from_code,
	cf.sign AS from_sign,

	ct.currency_id AS to_id,
	ct.code AS to_code,
	ct.sign AS to_sign,

	ex.created_at

from exchange_rate ex 

LEFT JOIN currency cf ON (ex.id_currency_from = cf.currency_id) 
LEFT JOIN currency ct ON (ex.id_currency_to = ct.currency_id);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `curcal`.`currency`
-- -----------------------------------------------------
START TRANSACTION;
USE `curcal`;
INSERT INTO `curcal`.`currency` (`currency_id`, `code`, `sign`) VALUES (1, 'USD', '&#36;');
INSERT INTO `curcal`.`currency` (`currency_id`, `code`, `sign`) VALUES (2, 'EUR', '&#8364');
INSERT INTO `curcal`.`currency` (`currency_id`, `code`, `sign`) VALUES (3, 'CHF', 'CHF');
INSERT INTO `curcal`.`currency` (`currency_id`, `code`, `sign`) VALUES (4, 'GBP', '&#8356;');
INSERT INTO `curcal`.`currency` (`currency_id`, `code`, `sign`) VALUES (5, 'JPY', '&#165');
INSERT INTO `curcal`.`currency` (`currency_id`, `code`, `sign`) VALUES (6, 'CAD', '&#36;');

COMMIT;


-- -----------------------------------------------------
-- Data for table `curcal`.`exchange_rate`
-- -----------------------------------------------------
START TRANSACTION;
USE `curcal`;
INSERT INTO `curcal`.`exchange_rate` (`exchange_rate_id`, `id_currency_from`, `id_currency_to`, `rate`, `created_at`) VALUES (1, 2, 1, 1.5897, NULL);
INSERT INTO `curcal`.`exchange_rate` (`exchange_rate_id`, `id_currency_from`, `id_currency_to`, `rate`, `created_at`) VALUES (2, 2, 3, 1.6135, NULL);
INSERT INTO `curcal`.`exchange_rate` (`exchange_rate_id`, `id_currency_from`, `id_currency_to`, `rate`, `created_at`) VALUES (3, 2, 4, 0.8031, NULL);
INSERT INTO `curcal`.`exchange_rate` (`exchange_rate_id`, `id_currency_from`, `id_currency_to`, `rate`, `created_at`) VALUES (4, 1, 5, 103.51, NULL);
INSERT INTO `curcal`.`exchange_rate` (`exchange_rate_id`, `id_currency_from`, `id_currency_to`, `rate`, `created_at`) VALUES (5, 3, 1, 0.986, NULL);
INSERT INTO `curcal`.`exchange_rate` (`exchange_rate_id`, `id_currency_from`, `id_currency_to`, `rate`, `created_at`) VALUES (6, 4, 6, 2.0174, NULL);

COMMIT;

